// <auto-generated />
using System;
using F237.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F237.DAL.Migrations
{
    [DbContext(typeof(F237DbContext))]
    [Migration("20260611233405_RenameVilleToPays")]
    partial class RenameVilleToPays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F237.Domain.Entities.ButMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstButCSC")
                        .HasColumnType("bit");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.HasIndex("MatchId");

                    b.ToTable("ButsMatch");
                });

            modelBuilder.Entity("F237.Domain.Entities.Classement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ButsContre")
                        .HasColumnType("int");

                    b.Property<int>("ButsPour")
                        .HasColumnType("int");

                    b.Property<int>("Defaites")
                        .HasColumnType("int");

                    b.Property<int>("DifferenceDesButs")
                        .HasColumnType("int");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<int>("MatchsJoues")
                        .HasColumnType("int");

                    b.Property<int>("Nuls")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.Property<int>("Victoires")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("SaisonId");

                    b.ToTable("Classements");
                });

            modelBuilder.Entity("F237.Domain.Entities.DemandeRetrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTraitement")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantFCFA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MontantPoints")
                        .HasColumnType("int");

                    b.Property<string>("NumereMobileMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("DemandesRetrait");
                });

            modelBuilder.Entity("F237.Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiFootballId")
                        .HasColumnType("int");

                    b.Property<int>("Division")
                        .HasColumnType("int");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("F237.Domain.Entities.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Nationalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreButs")
                        .HasColumnType("int");

                    b.Property<int>("NombreMatchs")
                        .HasColumnType("int");

                    b.Property<int>("NombrePasses")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("F237.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiFootballId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMatch")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeDomicileId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeExterieurId")
                        .HasColumnType("int");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreDomicile")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreExterieur")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeDomicileId");

                    b.HasIndex("EquipeExterieurId");

                    b.HasIndex("SaisonId");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("F237.Domain.Entities.Pari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePari")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GainPotentiel")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Mise")
                        .HasColumnType("int");

                    b.Property<int?>("PariGroupeId")
                        .HasColumnType("int");

                    b.Property<int>("Pronostic")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PariGroupeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Paris");
                });

            modelBuilder.Entity("F237.Domain.Entities.PariGroupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.ToTable("PariGroupes");
                });

            modelBuilder.Entity("F237.Domain.Entities.Saison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("Division")
                        .HasColumnType("int");

                    b.Property<bool>("EstActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Saisons");
                });

            modelBuilder.Entity("F237.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTransaction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("F237.Domain.Entities.Transfert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTransfert")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeArriveeId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeDepartId")
                        .HasColumnType("int");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeArriveeId");

                    b.HasIndex("EquipeDepartId");

                    b.HasIndex("JoueurId");

                    b.ToTable("Transferts");
                });

            modelBuilder.Entity("F237.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldePoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("F237.Domain.Entities.ButMatch", b =>
                {
                    b.HasOne("F237.Domain.Entities.Joueur", "Joueur")
                        .WithMany("Buts")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F237.Domain.Entities.Match", "Match")
                        .WithMany("Buts")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("F237.Domain.Entities.Classement", b =>
                {
                    b.HasOne("F237.Domain.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F237.Domain.Entities.Saison", "Saison")
                        .WithMany("Classements")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("F237.Domain.Entities.DemandeRetrait", b =>
                {
                    b.HasOne("F237.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("F237.Domain.Entities.Joueur", b =>
                {
                    b.HasOne("F237.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Joueurs")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("F237.Domain.Entities.Match", b =>
                {
                    b.HasOne("F237.Domain.Entities.Equipe", "EquipeDomicile")
                        .WithMany("MatchsDomicile")
                        .HasForeignKey("EquipeDomicileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F237.Domain.Entities.Equipe", "EquipeExterieur")
                        .WithMany("MatchsExterieur")
                        .HasForeignKey("EquipeExterieurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F237.Domain.Entities.Saison", "Saison")
                        .WithMany("Matchs")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipeDomicile");

                    b.Navigation("EquipeExterieur");

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("F237.Domain.Entities.Pari", b =>
                {
                    b.HasOne("F237.Domain.Entities.Match", "Match")
                        .WithMany("Paris")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F237.Domain.Entities.PariGroupe", "PariGroupe")
                        .WithMany("Paris")
                        .HasForeignKey("PariGroupeId");

                    b.HasOne("F237.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Paris")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("PariGroupe");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("F237.Domain.Entities.PariGroupe", b =>
                {
                    b.HasOne("F237.Domain.Entities.Utilisateur", "Createur")
                        .WithMany("PariGroupes")
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("F237.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("F237.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Transactions")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("F237.Domain.Entities.Transfert", b =>
                {
                    b.HasOne("F237.Domain.Entities.Equipe", "EquipeArrivee")
                        .WithMany()
                        .HasForeignKey("EquipeArriveeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F237.Domain.Entities.Equipe", "EquipeDepart")
                        .WithMany()
                        .HasForeignKey("EquipeDepartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F237.Domain.Entities.Joueur", "Joueur")
                        .WithMany()
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipeArrivee");

                    b.Navigation("EquipeDepart");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("F237.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("Joueurs");

                    b.Navigation("MatchsDomicile");

                    b.Navigation("MatchsExterieur");
                });

            modelBuilder.Entity("F237.Domain.Entities.Joueur", b =>
                {
                    b.Navigation("Buts");
                });

            modelBuilder.Entity("F237.Domain.Entities.Match", b =>
                {
                    b.Navigation("Buts");

                    b.Navigation("Paris");
                });

            modelBuilder.Entity("F237.Domain.Entities.PariGroupe", b =>
                {
                    b.Navigation("Paris");
                });

            modelBuilder.Entity("F237.Domain.Entities.Saison", b =>
                {
                    b.Navigation("Classements");

                    b.Navigation("Matchs");
                });

            modelBuilder.Entity("F237.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("PariGroupes");

                    b.Navigation("Paris");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
